### ISSUE TITLE
Do not delete sapstart.log

### ISSUE THREAD

**Issue by wegenerbenjamin** [chriselswede/hanacleaner#2]
Hi Chris,

in clean_trace_files, you mustn't delete the file sapstart.log, which is required by the SAP Host Agent to determine running processes (sounds stupid, but that's the way it is). We ran into this issue during the configuration of Focused Run (SAP-based Monitoring Tool). 

Best regards,
Benjamin

**Comment by chriselswede** [comment]
Awesome! Thanks a lot! Fixed now.
